### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by apptaro** [coderplus/m2e-connector-for-maven-remote-resources-plugin#3]
Cannot Install with the Update Site. The error is:
Unable to read repository at https://coderplus.com/m2e-update-sites/maven-remote-resources-plugin/content.xml.

Cannot install from Eclipse Marketplace Client, either.

**Comment by AndreOe** [comment]
Same for me.
This is the message in i am getting:

Problems occurred while performing installation: Error(s) occurred gathering items for installation
Error(s) occurred gathering items for installation
Unable to read repository at http://coderplus.com/m2e-update-sites/maven-remote-resources-plugin/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Error installing m2e connector for maven-remote-resources-plugin contacting repository http://coderplus.com/m2e-update-sites/maven-remote-resources-plugin/

**Comment by jackhai9** [comment]
@AndreOe  same error .

**Comment by michael-o** [comment]
Same error here: https://www.ssllabs.com/ssltest/analyze.html?d=coderplus.com&hideResults=on says that the cert chain is incomplete. That this probably the reason.

**Comment by aneesh-joseph** [comment]
apologies for the delayed response. The problem with the CA chain is sorted.. You can also use this alternate update site - https://coderplus.github.io/m2e-connector-for-maven-remote-resources-plugin/

**Comment by AndreOe** [comment]
Thanks

**Comment by 0815Hunter** [comment]
again not working.. content.xml unable to read.

**Comment by aneesh-joseph** [comment]
Should work ok now, thank you for reporting it quickly :)

**Comment by petersvahn** [comment]
I had a certificate problem with accessing the site, try with the following instead in 
Help->Install new software:
http://coderplus.github.io/m2e-connector-for-maven-remote-resources-plugin/
